package:
  name: spiceypy
  version: "2.1.1"

source:
  path: ../

build:
    number: 1

requirements:
    build:
        - python
        - setuptools
        - six
        - numpy >=1.12
        - certifi >=2017.1.23
        - pytest
    run:
        - python
        - setuptools
        - six
        - numpy >=1.12
        - certifi >=2017.1.23
        - pytest

test:
    imports:
        - spiceypy
    requires:
        - numpy >=1.12
        - pytest
        - six
        - certifi >=2017.1.23

about:
    home: https://github.com/AndrewAnnex/SpiceyPy
    license: MIT License
    summary: 'A Python Wrapper for the NAIF CSPICE Toolkit'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml